import { fetchCategories, fetchProducts } from './data.js';

export const state = {
    view: 'attract', // 'attract', 'menu', 'payment', 'success'
    category: null, // will be set after loading
    cart: [],
    orderNumber: null,
    categories: [],
    products: [],
    loading: true,
    tip: 0,
    orderType: 'eat-in', // 'eat-in', 'takeaway'
    paymentMethod: 'card', // 'card', 'counter'
    language: 'en', // 'en', 'nl', 'zh'
};

export const translations = {
    en: {
        touch_to_start: 'Touch to Start',
        dining_choice: 'Dining Choice',
        eat_in: 'Eat In',
        takeaway: 'Takeaway',
        your_order: 'Your Order',
        confirm_order: 'Confirm Order',
        total: 'Total',
        try_this: 'Try this?',
        add_it: 'Yes, add it!',
        no_thanks: 'No, thank you',
        support_team: 'Support our Team?',
        tip_msg: 'Would you like to add a €0.50 tip to support our hardworking kitchen staff?',
        yes_please: 'Yes, please!',
        no_support: 'No, thanks',
        pay_method: 'Payment Method',
        pay_card: 'Pay by Card',
        pay_counter: 'Pay at Counter',
        order_num: 'Order #',
        please_receipt: 'Please take your receipt.',
        proceed_counter: 'Please proceed to the counter to pay.',
        ready_shortly: 'Your food will be ready shortly.',
        finish: 'Finish',
        cancel: 'Cancel',
        tap_to_pay: 'Tap card above to pay',
        processing: 'Processing...',
        pay_approved: 'Payment Approved!',
        pay_failed: 'Payment failed. Please try again.',
        loading_menu: 'Loading menu...',
        items_in_order: 'Items in order',
        each: 'each',
        empty_cart: 'Your cart is empty',
        cart_empty_btn: 'Cart Empty',
        dining_msg: 'Will you be eating here or taking your meal to go?',
        payment_choice_msg: 'How would you like to pay for your order?',
        add: 'Add',
        kcal: 'kcal',
        select_language: 'Select a Language',
    },
    nl: {
        touch_to_start: 'Raak aan om te beginnen',
        dining_choice: 'Eetkeuze',
        eat_in: 'Hier eten',
        takeaway: 'Meenemen',
        your_order: 'Jouw bestelling',
        confirm_order: 'Bevestig bestelling',
        total: 'Totaal',
        try_this: 'Dit proberen?',
        add_it: 'Ja, voeg toe!',
        no_thanks: 'Nee, bedankt',
        support_team: 'Ondersteun ons team?',
        tip_msg: 'Wilt u een fooi van €0,50 toevoegen om ons hardwerkende keukenpersoneel te steunen?',
        yes_please: 'Ja, graag!',
        no_support: 'Nee, bedankt',
        pay_method: 'Betaalmethode',
        pay_card: 'Betaal met pin',
        pay_counter: 'Betaal bij de kassa',
        order_num: 'Bestelling #',
        please_receipt: 'Neem uw bon mee.',
        proceed_counter: 'Ga naar de kassa om te betalen.',
        ready_shortly: 'Uw eten is binnenkort klaar.',
        finish: 'Klaar',
        cancel: 'Annuleren',
        tap_to_pay: 'Houd uw pas tegen de terminal',
        processing: 'Verwerken...',
        pay_approved: 'Betaling goedgekeurd!',
        pay_failed: 'Betaling mislukt. Probeer het opnieuw.',
        loading_menu: 'Menu laden...',
        items_in_order: 'Items in bestelling',
        each: 'per stuk',
        empty_cart: 'Uw winkelwagen is leeg',
        cart_empty_btn: 'Lege wagen',
        dining_msg: 'Gaat u hier eten of neemt u het mee?',
        payment_choice_msg: 'Hoe wilt u betalen?',
        add: 'Toevoegen',
        kcal: 'kcal',
        select_language: 'Kies een taal',
    },
    zh: {
        touch_to_start: '点击开始',
        dining_choice: '用餐选择',
        eat_in: '堂食',
        takeaway: '外带',
        your_order: '您的订单',
        confirm_order: '确认订单',
        total: '总计',
        try_this: '试试这个？',
        add_it: '是的，加入！',
        no_thanks: '不，谢谢',
        support_team: '支持我们的团队？',
        tip_msg: '您想添加 €0.50 的小费来支持我们辛苦工作的厨房员工吗？',
        yes_please: '是的，请！',
        no_support: '不，谢谢',
        pay_method: '付款方式',
        pay_card: '刷卡支付',
        pay_counter: '柜台支付',
        order_num: '订单编号 #',
        please_receipt: '请取走您的收据。',
        proceed_counter: '请前往柜台付款。',
        ready_shortly: '您的食物很快就会准备好。',
        finish: '完成',
        cancel: '取消',
        tap_to_pay: '请在上方刷卡',
        processing: '处理中...',
        pay_approved: '付款已批准！',
        pay_failed: '付款失败，请重试。',
        loading_menu: '菜单加载中...',
        items_in_order: '订单中的商品',
        each: '每个',
        empty_cart: '您的购物车是空的',
        cart_empty_btn: '购物车为空',
        dining_msg: '您是在这里用餐还是带走？',
        payment_choice_msg: '您想如何支付您的订单？',
        add: '添加',
        kcal: '千卡',
        select_language: '选择语言',
    },
    la: {
        touch_to_start: 'Ad incipiendum tange',
        dining_choice: 'Electio convivii',
        eat_in: 'Hic edere',
        takeaway: 'Auferre',
        your_order: 'Mandatum tuum',
        confirm_order: 'Confirma mandatum',
        total: 'Summa',
        try_this: 'Hoc probare?',
        add_it: 'Ita, adde!',
        no_thanks: 'Non, gratias',
        support_team: 'Auxilium manipulo?',
        tip_msg: 'Visne €0.50 addere ad adiuvandum lanios nostros?',
        yes_please: 'Ita, quaeso!',
        no_support: 'Non, gratias',
        pay_method: 'Modus solvendi',
        pay_card: 'Chartula solvere',
        pay_counter: 'Ad tabulam solvere',
        order_num: 'Numerus #',
        please_receipt: 'Recipe apocha, quaeso.',
        proceed_counter: 'Perge ad tabulam pro solutione.',
        ready_shortly: 'Cibus tuus mox paratus erit.',
        finish: 'Exitus',
        cancel: 'Cancella',
        tap_to_pay: 'Tange chartulam supra',
        processing: 'Operatur...',
        pay_approved: 'Solutio probata!',
        pay_failed: 'Solutio fefellit. Repete.',
        loading_menu: 'Menu oneratur...',
        items_in_order: 'Res in mandato',
        each: 'per rem',
        empty_cart: 'Mandatum tuum vacuum est',
        cart_empty_btn: 'Vacuum est',
        dining_msg: 'Edere hic vis an auferre?',
        payment_choice_msg: 'Quomodo solvere vis?',
        add: 'Adde',
        kcal: 'kcal',
        select_language: 'Elige linguam',
    },
    eg: {
        touch_to_start: '𓂝 𓇳',
        dining_choice: '𓄿 𓊗',
        eat_in: '𓉐 𓀀',
        takeaway: '𓂻 𓀀',
        your_order: '𓆓 𓅓 𓏛',
        confirm_order: '𓏜 𓏛',
        total: '𓃗',
        try_this: '𓁻 𓏤',
        add_it: '𓂝 𓏤',
        no_thanks: '𓂜 𓏤',
        support_team: '𓀀 𓏪 𓄿',
        tip_msg: '𓎛 𓏊 𓏤',
        yes_please: '𓏜 𓏤',
        no_support: '𓂜 𓏤',
        pay_method: '𓊛 𓊗',
        pay_card: '𓏛 𓊗',
        pay_counter: '𓉐 𓊗',
        order_num: '𓄤 𓏤',
        please_receipt: '𓏛 𓏤',
        proceed_counter: '𓂻 𓉐',
        ready_shortly: '𓇳 𓏤',
        finish: '𓃗',
        cancel: '𓂜',
        tap_to_pay: '𓂝 𓏛',
        processing: '𓆓 𓏤',
        pay_approved: '𓄤 𓏤',
        pay_failed: '𓅓 𓄿',
        loading_menu: '𓁻 𓅓',
        items_in_order: '𓏪 𓏛',
        each: '𓏤',
        empty_cart: '𓅓 𓂜',
        cart_empty_btn: '𓂜',
        dining_msg: '𓉐 𓂻 ?',
        payment_choice_msg: '𓊛 𓏛 ?',
        add: '𓂝',
        kcal: '𓇳',
        select_language: '𓈎 𓊗',
    },
    pirate: {
        touch_to_start: 'Tap to Plunder',
        dining_choice: 'Where to Feast?',
        eat_in: 'Stable Hand',
        takeaway: 'Set Sail',
        your_order: 'The Bounty',
        confirm_order: 'Sign the Articles',
        total: 'Loot',
        try_this: 'Try this, ya bilge rat?',
        add_it: 'Aye, add it!',
        no_thanks: 'Belay that',
        support_team: 'Share the Booty?',
        tip_msg: 'Spare a doubloon for the galley crew?',
        yes_please: 'Aye, aye!',
        no_support: 'Not a copper',
        pay_method: 'How ye payin?',
        pay_card: 'Plastic Plank',
        pay_counter: 'The Captain\'s Desk',
        order_num: 'Mark #',
        please_receipt: 'Take yer map.',
        proceed_counter: 'Go to the Cap\'n to pay.',
        ready_shortly: 'Yer grog be ready soon.',
        finish: 'Done',
        cancel: 'Abandon Ship',
        tap_to_pay: 'Tap yer gold above',
        processing: 'Waitin...',
        pay_approved: 'The Loot is Ours!',
        pay_failed: 'The Chest be Empty.',
        loading_menu: 'Mappin the seas...',
        items_in_order: 'Items in the chest',
        each: 'per soul',
        empty_cart: 'The chest is empty',
        cart_empty_btn: 'No Loot',
        dining_msg: 'Feast here or take it to the seas?',
        payment_choice_msg: 'How ye handin over the gold?',
        add: 'Add',
        kcal: 'energy',
        select_language: 'Pick yer Tongue',
    },
    fr: {
        touch_to_start: 'Toucher pour commencer',
        dining_choice: 'Choix du repas',
        eat_in: 'Sur place',
        takeaway: 'À emporter',
        your_order: 'Votre commande',
        confirm_order: 'Confirmer la commande',
        total: 'Total',
        try_this: 'Essayer ceci ?',
        add_it: 'Oui, ajoutez-le !',
        no_thanks: 'Non, merci',
        support_team: 'Soutenir notre équipe ?',
        tip_msg: 'Aimeriez-vous ajouter un pourboire de 0,50 € pour soutenir notre personnel ?',
        yes_please: 'Oui, s\'il vous plaît !',
        no_support: 'Non, merci',
        pay_method: 'Mode de paiement',
        pay_card: 'Payer par carte',
        pay_counter: 'Payer au comptoir',
        order_num: 'Commande #',
        please_receipt: 'Veuillez prendre votre reçu.',
        proceed_counter: 'Veuillez vous rendre au comptoir pour payer.',
        ready_shortly: 'Votre repas sera prêt sous peu.',
        finish: 'Terminer',
        cancel: 'Annuler',
        tap_to_pay: 'Posez votre carte ci-dessus',
        processing: 'Traitement...',
        pay_approved: 'Paiement approuvé !',
        pay_failed: 'Le paiement a échoué. Veuillez réessayer.',
        loading_menu: 'Chargement du menu...',
        items_in_order: 'Articles commandés',
        each: 'chaque',
        empty_cart: 'Votre panier est vide',
        cart_empty_btn: 'Panier vide',
        dining_msg: 'Voulez-vous manger ici ou emporter votre repas ?',
        payment_choice_msg: 'Comment souhaitez-vous régler votre commande ?',
        add: 'Ajouter',
        kcal: 'kcal',
        select_language: 'Choisir une langue',
    },
    es: {
        touch_to_start: 'Toca para empezar',
        dining_choice: 'Opción de comida',
        eat_in: 'Para comer aquí',
        takeaway: 'Para llevar',
        your_order: 'Tu pedido',
        confirm_order: 'Confirmar pedido',
        total: 'Total',
        try_this: '¿Quieres probar esto?',
        add_it: '¡Sí, añádelo!',
        no_thanks: 'No, gracias',
        support_team: '¿Apoyar a nuestro equipo?',
        tip_msg: '¿Te gustaría añadir una propina de 0,50 € para nuestro personal?',
        yes_please: '¡Sí, por favor!',
        no_support: 'No, gracias',
        pay_method: 'Método de pago',
        pay_card: 'Pagar con tarjeta',
        pay_counter: 'Pagar en el mostrador',
        order_num: 'Pedido #',
        please_receipt: 'Por favor, tome su recibo.',
        proceed_counter: 'Por favor, diríjase al mostrador para pagar.',
        ready_shortly: 'Su comida estará lista pronto.',
        finish: 'Finalizar',
        cancel: 'Cancelar',
        tap_to_pay: 'Toque con la tarjeta arriba',
        processing: 'Procesando...',
        pay_approved: '¡Pago aprobado!',
        pay_failed: 'Pago fallido. Inténtelo de nuevo.',
        loading_menu: 'Cargando menú...',
        items_in_order: 'Artículos en el pedido',
        each: 'cada uno',
        empty_cart: 'Tu carrito está vacío',
        cart_empty_btn: 'Carrito vacío',
        dining_msg: '¿Comerá aquí o es para llevar?',
        payment_choice_msg: '¿Cómo desea pagar su pedido?',
        add: 'Añadir',
        kcal: 'kcal',
        select_language: 'Seleccionar idioma',
    },
    de: {
        touch_to_start: 'Zum Starten berühren',
        dining_choice: 'Speiseauswahl',
        eat_in: 'Hier essen',
        takeaway: 'Mitnehmen',
        your_order: 'Ihre Bestellung',
        confirm_order: 'Bestellung bestätigen',
        total: 'Gesamt',
        try_this: 'Das hier probieren?',
        add_it: 'Ja, hinzufügen!',
        no_thanks: 'Nein, danke',
        support_team: 'Unser Team unterstützen?',
        tip_msg: 'Möchten Sie ein Trinkgeld von 0,50 € hinzufügen, um unser Küchenteam zu unterstützen?',
        yes_please: 'Ja, bitte!',
        no_support: 'Nein, danke',
        pay_method: 'Zahlungsmethode',
        pay_card: 'Mit Karte zahlen',
        pay_counter: 'An der Kasse zahlen',
        order_num: 'Bestellnummer #',
        please_receipt: 'Bitte nehmen Sie Ihren Beleg.',
        proceed_counter: 'Bitte gehen Sie zur Kasse, um zu bezahlen.',
        ready_shortly: 'Ihre Speisen sind bald fertig.',
        finish: 'Fertig',
        cancel: 'Abbrechen',
        tap_to_pay: 'Karte oben auflegen',
        processing: 'Wird verarbeitet...',
        pay_approved: 'Zahlung genehmigt!',
        pay_failed: 'Zahlung fehlgeschlagen. Bitte erneut versuchen.',
        loading_menu: 'Menü wird geladen...',
        items_in_order: 'Artikel in der Bestellung',
        each: 'je',
        empty_cart: 'Ihr Warenkorb ist leer',
        cart_empty_btn: 'Warenkorb leer',
        dining_msg: 'Möchten Sie hier essen oder Ihre Mahlzeit mitnehmen?',
        payment_choice_msg: 'Wie möchten Sie Ihre Bestellung bezahlen?',
        add: 'Hinzufügen',
        kcal: 'kcal',
        select_language: 'Sprache auswählen',
    },
    it: {
        touch_to_start: 'Tocca per iniziare',
        dining_choice: 'Scelta del pasto',
        eat_in: 'Mangia qui',
        takeaway: 'Da asporto',
        your_order: 'Il tuo ordine',
        confirm_order: 'Conferma ordine',
        total: 'Totale',
        try_this: 'Provare questo?',
        add_it: 'Sì, aggiungilo!',
        no_thanks: 'No, grazie',
        support_team: 'Sostenere il nostro team?',
        tip_msg: 'Ti piacerebbe aggiungere una mancia di 0,50 € per sostenere il nostro staff in cucina?',
        yes_please: 'Sì, per favore!',
        no_support: 'No, grazie',
        pay_method: 'Metodo di pagamento',
        pay_card: 'Paga con carta',
        pay_counter: 'Paga alla cassa',
        order_num: 'Ordine #',
        please_receipt: 'Prendi la ricevuta, per favore.',
        proceed_counter: 'Prego, vai alla cassa per pagare.',
        ready_shortly: 'Il tuo cibo sarà pronto tra poco.',
        finish: 'Termina',
        cancel: 'Annulla',
        tap_to_pay: 'Tocca con la carta sopra',
        processing: 'Elaborazione...',
        pay_approved: 'Pagamento approvato!',
        pay_failed: 'Pagamento fallito. Riprova.',
        loading_menu: 'Caricamento menu...',
        items_in_order: 'Articoli nell\'ordine',
        each: 'cadauno',
        empty_cart: 'Il tuo carrello è vuoto',
        cart_empty_btn: 'Carrello vuoto',
        dining_msg: 'Vuoi mangiare qui o portare via il tuo pasto?',
        payment_choice_msg: 'Come vorresti pagare il tuo ordine?',
        add: 'Aggiungi',
        kcal: 'kcal',
        select_language: 'Seleziona una lingua',
    },
    jp: {
        touch_to_start: 'タッチしてスタート',
        dining_choice: 'お食事場所',
        eat_in: '店内で食べる',
        takeaway: 'テイクアウト',
        your_order: 'ご注文',
        confirm_order: '注文を確定する',
        total: '合計',
        try_this: 'こちらもいかがですか？',
        add_it: 'はい、追加します！',
        no_thanks: 'いいえ、結構です',
        support_team: 'スタッフを応援しますか？',
        tip_msg: 'キッチンのスタッフを応援するために、0.50ユーロのチップを追加しますか？',
        yes_please: 'はい、お願いします！',
        no_support: 'いいえ、結構です',
        pay_method: 'お支払い方法',
        pay_card: 'カードで払う',
        pay_counter: 'レジで払う',
        order_num: '注文番号 #',
        please_receipt: 'レシートをお受け取りください。',
        proceed_counter: 'レジへお進みください。',
        ready_shortly: 'まもなくお食事が用意できます。',
        finish: '完了',
        cancel: 'キャンセル',
        tap_to_pay: '上にカードをタッチしてください',
        processing: '処理中...',
        pay_approved: '決済が承認されました！',
        pay_failed: '決済に失敗しました。もう一度お試しください。',
        loading_menu: 'メニューを読み込んでいます...',
        items_in_order: '注文内容',
        each: '単価',
        empty_cart: 'カートは空です',
        cart_empty_btn: 'カートが空です',
        dining_msg: '店内でお召し上がりですか？それともお持ち帰りですか？',
        payment_choice_msg: 'お支払い方法を選んでください',
        add: '追加',
        kcal: 'kcal',
        select_language: '言語を選択',
    },
    kr: {
        touch_to_start: '터치하여 시작하기',
        dining_choice: '식사 옵션',
        eat_in: '매장 식사',
        takeaway: '포장하기',
        your_order: '내 주문 내역',
        confirm_order: '주문 확정하기',
        total: '총 합계',
        try_this: '이 메뉴도 드셔보시겠어요?',
        add_it: '네, 추가할게요!',
        no_thanks: '아니요, 괜찮습니다',
        support_team: '저희 팀을 응원해주시겠어요?',
        tip_msg: '열심히 일하는 주방 팀을 위해 0.50€의 팁을 추가하시겠습니까?',
        yes_please: '네, 추가합니다!',
        no_support: '아니요, 괜찮습니다',
        pay_method: '결제 수단 선택',
        pay_card: '카드로 결제',
        pay_counter: '카운터에서 결제',
        order_num: '주문 번호 #',
        please_receipt: '영수증을 챙겨주세요.',
        proceed_counter: '결제를 위해 카운터로 향해주세요.',
        ready_shortly: '주문하신 음식이 곧 준비됩니다.',
        finish: '완료',
        cancel: '취소',
        tap_to_pay: '상단에 카드를 대주세요',
        processing: '처리 중...',
        pay_approved: '결제가 승인되었습니다!',
        pay_failed: '결제에 실패했습니다. 다시 시도해주세요.',
        loading_menu: '메뉴를 불러오는 중...',
        items_in_order: '주문 상품 목록',
        each: '개당',
        empty_cart: '장바구니가 비어 있습니다',
        cart_empty_btn: '장바구니 비어있음',
        dining_msg: '매장에서 드시겠습니까, 아니면 포장하시겠습니까?',
        payment_choice_msg: '어떤 방법으로 결제하시겠습니까?',
        add: '추가',
        kcal: 'kcal',
        select_language: '언어 선택',
    },
    ru: {
        touch_to_start: 'Нажмите, чтобы начать',
        dining_choice: 'Где будете есть?',
        eat_in: 'В заведении',
        takeaway: 'С собой',
        your_order: 'Ваш заказ',
        confirm_order: 'Подтвердить заказ',
        total: 'Итого',
        try_this: 'Попробуете это?',
        add_it: 'Да, добавьте!',
        no_thanks: 'Нет, спасибо',
        support_team: 'Поддержать команду?',
        tip_msg: 'Хотите добавить чаевые в размере 0,50 €, чтобы поддержать нашу команду кухни?',
        yes_please: 'Да, пожалуйста!',
        no_support: 'Нет, спасибо',
        pay_method: 'Способ оплаты',
        pay_card: 'Оплата картой',
        pay_counter: 'Оплата на кассе',
        order_num: 'Номер заказа #',
        please_receipt: 'Пожалуйста, возьмите чек.',
        proceed_counter: 'Пожалуйста, пройдите на кассу для оплаты.',
        ready_shortly: 'Ваша еда скоро будет готова.',
        finish: 'Завершить',
        cancel: 'Отмена',
        tap_to_pay: 'Приложите карту выше',
        processing: 'Обработка...',
        pay_approved: 'Оплата одобрена!',
        pay_failed: 'Ошибка оплаты. Попробуйте снова.',
        loading_menu: 'Загрузка меню...',
        items_in_order: 'Товары в заказе',
        each: 'за шт.',
        empty_cart: 'Ваша корзина пуста',
        cart_empty_btn: 'Корзина пуста',
        dining_msg: 'Вы будете есть здесь или возьмете с собой?',
        payment_choice_msg: 'Как вы хотите оплатить заказ?',
        add: 'Добавить',
        kcal: 'ккал',
        select_language: 'Выберите язык',
    },
    pt: {
        touch_to_start: 'Toque para começar',
        dining_choice: 'Opção de refeição',
        eat_in: 'Comer aqui',
        takeaway: 'Para levar',
        your_order: 'Seu pedido',
        confirm_order: 'Confirmar pedido',
        total: 'Total',
        try_this: 'Experimentar isto?',
        add_it: 'Sim, adicione!',
        no_thanks: 'Não, obrigado',
        support_team: 'Apoiar nossa equipe?',
        tip_msg: 'Gostaria de adicionar uma gorjeta de 0,50 € para apoiar nossa equipe de cozinha?',
        yes_please: 'Sim, por favor!',
        no_support: 'Não, obrigado',
        pay_method: 'Método de pagamento',
        pay_card: 'Pagar com cartão',
        pay_counter: 'Pagar no balcão',
        order_num: 'Pedido #',
        please_receipt: 'Por favor, retire seu recibo.',
        proceed_counter: 'Por favor, dirija-se ao balcão para pagar.',
        ready_shortly: 'Sua comida estará pronta em breve.',
        finish: 'Concluir',
        cancel: 'Cancelar',
        tap_to_pay: 'Encoste o cartão acima',
        processing: 'Processando...',
        pay_approved: 'Pagamento aprovado!',
        pay_failed: 'Falha no pagamento. Tente novamente.',
        loading_menu: 'Carregando menu...',
        items_in_order: 'Itens no pedido',
        each: 'cada',
        empty_cart: 'Seu carrinho está vazio',
        cart_empty_btn: 'Carrinho vazio',
        dining_msg: 'Deseja comer aqui ou levar seu pedido?',
        payment_choice_msg: 'Como você gostaria de pagar seu pedido?',
        add: 'Adicionar',
        kcal: 'kcal',
        select_language: 'Selecionar idioma',
    },
    el: {
        touch_to_start: 'Αγγίξτε για έναρξη',
        dining_choice: 'Επιλογή γεύματος',
        eat_in: 'Εδώ',
        takeaway: 'Σε πακέτο',
        your_order: 'Η παραγγελία σας',
        confirm_order: 'Επιβεβαίωση παραγγελίας',
        total: 'Σύνολο',
        try_this: 'Δοκιμάστε αυτό;',
        add_it: 'Ναι, προσθήκη!',
        no_thanks: 'Όχι, ευχαριστώ',
        support_team: 'Υποστηρίξτε την ομάδα μας;',
        tip_msg: 'Θα θέλατε να προσθέσετε φιλοδώρημα 0,50 € για να υποστηρίξετε το προσωπικό της κουζίνας μας;',
        yes_please: 'Ναι, παρακαλώ!',
        no_support: 'Όχι, ευχαριστώ',
        pay_method: 'Τρόπος πληρωμής',
        pay_card: 'Πληρωμή με κάρτα',
        pay_counter: 'Πληρωμή στο ταμείο',
        order_num: 'Αριθμός παραγγελίας #',
        please_receipt: 'Παρακαλώ πάρτε την απόδειξή σας.',
        proceed_counter: 'Παρακαλώ προχωρήστε στο ταμείο για την πληρωμή.',
        ready_shortly: 'Το φαγητό σας θα είναι έτοιμο σε λίγο.',
        finish: 'Τέλος',
        cancel: 'Ακύρωση',
        tap_to_pay: 'Ακουμπήστε την κάρτα πάνω',
        processing: 'Επεξεργασία...',
        pay_approved: 'Η πληρωμή εγκρίθηκε!',
        pay_failed: 'Η πληρωμή απέτυχε. Δοκιμάστε ξανά.',
        loading_menu: 'Φόρτωση μενού...',
        items_in_order: 'Είδη στην παραγγελία',
        each: 'το καθένα',
        empty_cart: 'Το καλάθι σας είναι άδειο',
        cart_empty_btn: 'Άδειο καλάθι',
        dining_msg: 'Θα φάτε εδώ ή θα πάρετε το γεύμα σας πακέτο;',
        payment_choice_msg: 'Πώς θα θέλατε να πληρώσετε για την παραγγελία σας;',
        add: 'Προσθήκη',
        kcal: 'kcal',
        select_language: 'Επιλογή γλώσσας',
    },
    tr: {
        touch_to_start: 'Başlamak için dokunun',
        dining_choice: 'Yemek seçimi',
        eat_in: 'Burada ye',
        takeaway: 'Paket servis',
        your_order: 'Siparişiniz',
        confirm_order: 'Siparişi onayla',
        total: 'Toplam',
        try_this: 'Bunu denemek ister misiniz?',
        add_it: 'Evet, ekle!',
        no_thanks: 'Hayır, teşekkürler',
        support_team: 'Ekibimizi destekleyin?',
        tip_msg: 'Mutfak ekibimizi desteklemek için 0,50 € bahşiş eklemek ister misiniz?',
        yes_please: 'Evet, lütfen!',
        no_support: 'Hayır, teşekkürler',
        pay_method: 'Ödeme yöntemi',
        pay_card: 'Kartla öde',
        pay_counter: 'Kasada öde',
        order_num: 'Sipariş No #',
        please_receipt: 'Lütfen fişinizi alın.',
        proceed_counter: 'Lütfen ödeme için kasaya ilerleyin.',
        ready_shortly: 'Yemeğiniz kısa süre içinde hazır olacak.',
        finish: 'Bitir',
        cancel: 'İptal',
        tap_to_pay: 'Kartı yukarıya dokundurun',
        processing: 'İşleniyor...',
        pay_approved: 'Ödeme onaylandı!',
        pay_failed: 'Ödeme başarısız. Lütfen tekrar deneyin.',
        loading_menu: 'Menü yükleniyor...',
        items_in_order: 'Siparişteki ürünler',
        each: 'adet',
        empty_cart: 'Sepetiniz boş',
        cart_empty_btn: 'Sepet boş',
        dining_msg: 'Burada mı yiyeceksiniz yoksa paket mi alacaksınız?',
        payment_choice_msg: 'Siparişinizi nasıl ödemek istersiniz?',
        add: 'Ekle',
        kcal: 'kcal',
        select_language: 'Dil seçin',
    },
    ar: {
        touch_to_start: 'المس للبدء',
        dining_choice: 'خيار الأكل',
        eat_in: 'الأكل هنا',
        takeaway: 'سفري',
        your_order: 'طلبك',
        confirm_order: 'تأكيد الطلب',
        total: 'المجموع',
        try_this: 'جرب هذا؟',
        add_it: 'نعم، أضفه!',
        no_thanks: 'لا، شكراً',
        support_team: 'دعم فريقنا؟',
        tip_msg: 'هل ترغب في إضافة إكرامية بقيمة 0.50 يورو لدعم طاقم المطبخ المجتهد؟',
        yes_please: 'نعم، من فضلك!',
        no_support: 'لا، شكراً',
        pay_method: 'طريقة الدفع',
        pay_card: 'الدفع بالبطاقة',
        pay_counter: 'الدفع عند الكاونتر',
        order_num: 'رقم الطلب #',
        please_receipt: 'يرجى أخذ الإيصال الخاص بك.',
        proceed_counter: 'يرجى التوجه إلى الكاونتر للدفع.',
        ready_shortly: 'سيكون طعامك جاهزاً قريباً.',
        finish: 'إنهاء',
        cancel: 'إلغاء',
        tap_to_pay: 'مرر البطاقة في الأعلى للدفع',
        processing: 'جاري المعالجة...',
        pay_approved: 'تمت الموافقة على الدفع!',
        pay_failed: 'فشل الدفع. يرجى المحاولة مرة أخرى.',
        loading_menu: 'جاري تحميل القائمة...',
        items_in_order: 'الأصناف في الطلب',
        each: 'للكل',
        empty_cart: 'سلة التسوق فارغة',
        cart_empty_btn: 'السلة فارغة',
        dining_msg: 'هل ستأكل هنا أم ستأخذ وجبتك معك؟',
        payment_choice_msg: 'كيف ترغب في دفع ثمن طلبك؟',
        add: 'إضافة',
        kcal: 'سعرة',
        select_language: 'اختر اللغة',
    },
    hi: {
        touch_to_start: 'शुरू करने के लिए छुएं',
        dining_choice: 'खाने का विकल्प',
        eat_in: 'यहीं खाएं',
        takeaway: 'साथ ले जाएं',
        your_order: 'आपका ऑर्डर',
        confirm_order: 'ऑर्डर की पुष्टि करें',
        total: 'कुल योग',
        try_this: 'इसे आज़माएं?',
        add_it: 'हाँ, इसे जोड़ें!',
        no_thanks: 'नहीं, धन्यवाद',
        support_team: 'हमारी टीम का समर्थन करें?',
        tip_msg: 'क्या आप हमारे मेहनती रसोई कर्मचारियों का समर्थन करने के लिए 0.50€ की टिप जोड़ना चाहेंगे?',
        yes_please: 'हाँ, कृपया!',
        no_support: 'नहीं, धन्यवाद',
        pay_method: 'भुगतान का तरीका',
        pay_card: 'कार्ड से भुगतान',
        pay_counter: 'काउंटर पर भुगतान',
        order_num: 'ऑर्डर संख्या #',
        please_receipt: 'कृपया अपनी रसीद लें।',
        proceed_counter: 'भुगतान के लिए कृपया काउंटर पर जाएं।',
        ready_shortly: 'आपका खाना जल्द ही तैयार हो जाएगा।',
        finish: 'समाप्त',
        cancel: 'रद्द करें',
        tap_to_pay: 'भुगतान के लिए कार्ड ऊपर टैप करें',
        processing: 'प्रक्रिया चल रही है...',
        pay_approved: 'भुगतान स्वीकृत!',
        pay_failed: 'भुगतान विफल। कृपया पुनः प्रयास करें।',
        loading_menu: 'मेनू लोड हो रहा है...',
        items_in_order: 'ऑर्डर में सामग्रियां',
        each: 'प्रत्येक',
        empty_cart: 'आपकी कार्ट खाली है',
        cart_empty_btn: 'कार्ट खाली है',
        dining_msg: 'क्या आप यहीं खाएंगे या भोजन साथ ले जाएंगे?',
        payment_choice_msg: 'आप अपने ऑर्डर का भुगतान कैसे करना चाहेंगे?',
        add: 'जोड़ें',
        kcal: 'kcal',
        select_language: 'भाषा चुनें',
    },
    vi: {
        touch_to_start: 'Chạm để bắt đầu',
        dining_choice: 'Lựa chọn ăn uống',
        eat_in: 'Ăn tại đây',
        takeaway: 'Mang đi',
        your_order: 'Đơn hàng của bạn',
        confirm_order: 'Xác nhận đơn hàng',
        total: 'Tổng cộng',
        try_this: 'Thử món này nhé?',
        add_it: 'Vâng, thêm vào!',
        no_thanks: 'Không, cảm ơn',
        support_team: 'Ủng hộ đội ngũ của chúng tôi?',
        tip_msg: 'Bạn có muốn thêm 0,50€ tiền boa để ủng hộ đội ngũ nhân viên bếp làm việc chăm chỉ của chúng tôi không?',
        yes_please: 'Vâng, làm ơn!',
        no_support: 'Không, cảm ơn',
        pay_method: 'Phương thức thanh toán',
        pay_card: 'Thanh toán bằng thẻ',
        pay_counter: 'Thanh toán tại quầy',
        order_num: 'Mã đơn hàng #',
        please_receipt: 'Vui lòng nhận biên lai của bạn.',
        proceed_counter: 'Vui lòng đến quầy để thanh toán.',
        ready_shortly: 'Thức ăn của bạn sẽ sớm sẵn sàng.',
        finish: 'Hoàn tất',
        cancel: 'Hủy bỏ',
        tap_to_pay: 'Chạm thẻ lên trên để thanh toán',
        processing: 'Đang xử lý...',
        pay_approved: 'Thanh toán thành công!',
        pay_failed: 'Thanh toán thất bại. Vui lòng thử lại.',
        loading_menu: 'Đang tải thực đơn...',
        items_in_order: 'Món trong đơn hàng',
        each: 'mỗi món',
        empty_cart: 'Giỏ hàng của bạn đang trống',
        cart_empty_btn: 'Giỏ hàng trống',
        dining_msg: 'Bạn sẽ ăn tại đây hay mang theo suất ăn của mình?',
        payment_choice_msg: 'Bạn muốn thanh toán đơn hàng của mình như thế nào?',
        add: 'Thêm',
        kcal: 'kcal',
        select_language: 'Chọn ngôn ngữ',
    },
    th: {
        touch_to_start: 'แตะเพื่อเริ่ม',
        dining_choice: 'ตัวเลือกการรับประทาน',
        eat_in: 'ทานที่นี่',
        takeaway: 'สั่งกลับบ้าน',
        your_order: 'รายการอาหารของคุณ',
        confirm_order: 'ยืนยันรายการสั่งซื้อ',
        total: 'ยอดรวมทั้งหมด',
        try_this: 'ลองสิ่งนี้ดูไหม?',
        add_it: 'ใช่ เพิ่มเลย!',
        no_thanks: 'ไม่ ขอบคุณ',
        support_team: 'สนับสนุนทีมงานของเรา?',
        tip_msg: 'คุณต้องการเพิ่มทิป 0.50 ยูโรเพื่อสนับสนุนพนักงานในครัวที่ทำงานหนักของเราหรือไม่?',
        yes_please: 'ใช่ ได้โปรด!',
        no_support: 'ไม่ ขอบคุณ',
        pay_method: 'วิธีการชำระเงิน',
        pay_card: 'ชำระด้วยบัตร',
        pay_counter: 'ชำระที่เคาน์เตอร์',
        order_num: 'หมายเลขรายการ #',
        please_receipt: 'โปรดรับใบเสร็จของคุณ',
        proceed_counter: 'โปรดไปที่เคาน์เตอร์เพื่อชำระเงิน',
        ready_shortly: 'อาหารของคุณจะพร้อมในอีกไม่ช้า',
        finish: 'เสร็จสิ้น',
        cancel: 'ยกเลิก',
        tap_to_pay: 'แตะบัตรด้านบนเพื่อชำระเงิน',
        processing: 'กำลังดำเนินการ...',
        pay_approved: 'ชำระเงินอนุมัติแล้ว!',
        pay_failed: 'ชำระเงินล้มเหลว โปรดลองอีกครั้ง',
        loading_menu: 'กำลังโหลดเมนู...',
        items_in_order: 'รายการในคำสั่งซื้อ',
        each: 'ชิ้นละ',
        empty_cart: 'ตระกร้าของคุณว่างเปล่า',
        cart_empty_btn: 'ตระกร้าว่าง',
        dining_msg: 'คุณจะรับประทานที่นี่หรือจะสั่งกลับบ้าน?',
        payment_choice_msg: 'คุณต้องการชำระเงินสำหรับรายการสั่งซื้อของคุณอย่างไร?',
        add: 'เพิ่ม',
        kcal: 'kcal',
        select_language: 'เลือกภาษา',
    },
    pl: {
        touch_to_start: 'Dotknij, aby rozpocząć',
        dining_choice: 'Wybór posiłku',
        eat_in: 'Na miejscu',
        takeaway: 'Na wynos',
        your_order: 'Twoje zamówienie',
        confirm_order: 'Potwierdź zamówienie',
        total: 'Suma',
        try_this: 'Chcesz spróbować tego?',
        add_it: 'Tak, dodaj!',
        no_thanks: 'Nie, dziękuję',
        support_team: 'Wesprzyj nasz zespół?',
        tip_msg: 'Czy chcesz dodać 0,50€ napiwku, aby wesprzeć nasz ciężko pracujący zespół kuchenny?',
        yes_please: 'Tak, poproszę!',
        no_support: 'Nie, dziękuję',
        pay_method: 'Metoda płatności',
        pay_card: 'Zapłać kartą',
        pay_counter: 'Zapłać przy kasie',
        order_num: 'Numer zamówienia #',
        please_receipt: 'Proszę odebrać paragon.',
        proceed_counter: 'Proszę podejść do kasy, aby zapłacić.',
        ready_shortly: 'Twoje jedzenie będzie wkrótce gotowe.',
        finish: 'Zakończ',
        cancel: 'Anuluj',
        tap_to_pay: 'Przyłóż kartę powyżej',
        processing: 'Przetwarzanie...',
        pay_approved: 'Płatność zatwierdzona!',
        pay_failed: 'Płatność nieudana. Spróbuj ponownie.',
        loading_menu: 'Ładowanie menu...',
        items_in_order: 'Produkty w zamówieniu',
        each: 'za szt.',
        empty_cart: 'Twój koszyk jest pusty',
        cart_empty_btn: 'Koszyk pusty',
        dining_msg: 'Zjesz na miejscu czy weźmiesz posiłek na wynos?',
        payment_choice_msg: 'Jak chcesz zapłacić za zamówienie?',
        add: 'Dodaj',
        kcal: 'kcal',
        select_language: 'Wybierz język',
    },
    sv: {
        touch_to_start: 'Rör för att starta',
        dining_choice: 'Måltidsval',
        eat_in: 'Ät här',
        takeaway: 'Ta med',
        your_order: 'Din beställning',
        confirm_order: 'Bekräfta beställning',
        total: 'Totalt',
        try_this: 'Prova det här?',
        add_it: 'Ja, lägg till!',
        no_thanks: 'Nej tack',
        support_team: 'Stöd vårt team?',
        tip_msg: 'Vill du lägga till 0,50€ dricks för att stödja vår hårt arbetande kökspersonal?',
        yes_please: 'Ja tack!',
        no_support: 'Nej tack',
        pay_method: 'Betalningsmetod',
        pay_card: 'Betala med kort',
        pay_counter: 'Betala i kassan',
        order_num: 'Ordernummer #',
        please_receipt: 'Vänligen ta ditt kvitto.',
        proceed_counter: 'Vänligen gå till kassan för att betala.',
        ready_shortly: 'Din mat är klar snart.',
        finish: 'Slutför',
        cancel: 'Avbryt',
        tap_to_pay: 'Blippa kortet ovanför',
        processing: 'Bearbetar...',
        pay_approved: 'Betalning godkänd!',
        pay_failed: 'Betalning misslyckades. Försök igen.',
        loading_menu: 'Laddar menyn...',
        items_in_order: 'Artiklar i ordern',
        each: 'st',
        empty_cart: 'Din varukorg är tom',
        cart_empty_btn: 'Varukorg tom',
        dining_msg: 'Ska du äta här eller ta med dig maten?',
        payment_choice_msg: 'Hur vill du betala för din beställning?',
        add: 'Lägg till',
        kcal: 'kcal',
        select_language: 'Välj språk',
    },
    no: {
        touch_to_start: 'Berør for å starte',
        dining_choice: 'Måltidsvalg',
        eat_in: 'Spis her',
        takeaway: 'Ta med',
        your_order: 'Din bestilling',
        confirm_order: 'Bekreft bestilling',
        total: 'Totalt',
        try_this: 'Prøve dette?',
        add_it: 'Ja, legg det til!',
        no_thanks: 'Nei takk',
        support_team: 'Støtt teamet vårt?',
        tip_msg: 'Vil du legge til 0,50€ i tips for å støtte våre hardtarbeidende kjøkkenansatte?',
        yes_please: 'Ja takk!',
        no_support: 'Nei takk',
        pay_method: 'Betalingsmetode',
        pay_card: 'Betal med kort',
        pay_counter: 'Betal i kassen',
        order_num: 'Bestillingsnummer #',
        please_receipt: 'Vennligst ta kvitteringen din.',
        proceed_counter: 'Vennligst gå til kassen for å betale.',
        ready_shortly: 'Maten din er klar snart.',
        finish: 'Fullfør',
        cancel: 'Avbryt',
        tap_to_pay: 'Tæpp kortet over',
        processing: 'Behandler...',
        pay_approved: 'Betaling godkjent!',
        pay_failed: 'Betaling mislyktes. Prøv igjen.',
        loading_menu: 'Laster meny...',
        items_in_order: 'Varer i bestillingen',
        each: 'per stk',
        empty_cart: 'Handlekurven din er tom',
        cart_empty_btn: 'Tom kurv',
        dining_msg: 'Skal du spise her eller ta med maten?',
        payment_choice_msg: 'Hvordan ønsker du å betale for bestillingen?',
        add: 'Legg til',
        kcal: 'kcal',
        select_language: 'Velg språk',
    },
    da: {
        touch_to_start: 'Rør for at starte',
        dining_choice: 'Måltidsvalg',
        eat_in: 'Spis her',
        takeaway: 'Tag med',
        your_order: 'Din bestilling',
        confirm_order: 'Bekræft bestilling',
        total: 'Total',
        try_this: 'Prøv dette?',
        add_it: 'Ja, tilføj det!',
        no_thanks: 'Nej tak',
        support_team: 'Støt vores team?',
        tip_msg: 'Vil du tilføje 0,50€ i drikkepenge for at støtte vores hårdtarbejdende køkkenpersonale?',
        yes_please: 'Ja tak!',
        no_support: 'Nej tak',
        pay_method: 'Betalingsmetode',
        pay_card: 'Betal med kort',
        pay_counter: 'Betal ved kassen',
        order_num: 'Ordrenummer #',
        please_receipt: 'Værsgo, tag din kvittering.',
        proceed_counter: 'Gå venligst til kassen for at betale.',
        ready_shortly: 'Din mad er klar om lidt.',
        finish: 'Afslut',
        cancel: 'Annuller',
        tap_to_pay: 'Bliptr kortet ovenfor',
        processing: 'Behandler...',
        pay_approved: 'Betaling godkendt!',
        pay_failed: 'Betaling fejlede. Prøv igen.',
        loading_menu: 'Indlæser menu...',
        items_in_order: 'Varer i ordren',
        each: 'stk',
        empty_cart: 'Din kurv er tom',
        cart_empty_btn: 'Kurv tom',
        dining_msg: 'Vil du spise her eller tage din mad med?',
        payment_choice_msg: 'Hvordan vil du betale for din bestilling?',
        add: 'Tilføj',
        kcal: 'kcal',
        select_language: 'Vælg sprog',
    },
    fi: {
        touch_to_start: 'Kosketa aloittaaksesi',
        dining_choice: 'Ateriavaihtoehto',
        eat_in: 'Syö täällä',
        takeaway: 'Mukaan',
        your_order: 'Tilauksesi',
        confirm_order: 'Vahvista tilaus',
        total: 'Yhteensä',
        try_this: 'Kokeile tätä?',
        add_it: 'Kyllä, lisää se!',
        no_thanks: 'Ei kiitos',
        support_team: 'Tue tiimiämme?',
        tip_msg: 'Haluaisitko lisätä 0,50 € tippiä tukeaksesi ahkeraa keittiöhenkilökuntaamme?',
        yes_please: 'Kyllä kiitos!',
        no_support: 'Ei kiitos',
        pay_method: 'Maksutapa',
        pay_card: 'Maksa kortilla',
        pay_counter: 'Maksa kassalla',
        order_num: 'Tilausnumero #',
        please_receipt: 'Ole hyvä ja ota kuitti.',
        proceed_counter: 'Ole hyvä ja siirry kassalle maksamaan.',
        ready_shortly: 'Ruokasi on valmista pian.',
        finish: 'Lopeta',
        cancel: 'Peruuta',
        tap_to_pay: 'Lähimaksa kortilla yläpuolella',
        processing: 'Käsitellään...',
        pay_approved: 'Maksu hyväksytty!',
        pay_failed: 'Maksu epäonnistui. Yritä uudelleen.',
        loading_menu: 'Ladataan valikkoa...',
        items_in_order: 'Tuotteet tilauksessa',
        each: 'kpl',
        empty_cart: 'Ostoskorisi on tyhjä',
        cart_empty_btn: 'Kori tyhjä',
        dining_msg: 'Syötkö täällä vai otatko aterian mukaan?',
        payment_choice_msg: 'Miten haluat maksaa tilauksesi?',
        add: 'Lisää',
        kcal: 'kcal',
        select_language: 'Valitse kieli',
    },

};

export const availableLanguages = [
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
    { code: 'zh', name: '中文', flag: '🇨🇳' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'it', name: 'Italiano', flag: '🇮🇹' },
    { code: 'jp', name: '日本語', flag: '🇯🇵' },
    { code: 'kr', name: '한국어', flag: '🇰🇷' },
    { code: 'ru', name: 'Русский', flag: '🇷🇺' },
    { code: 'pt', name: 'Português', flag: '🇵🇹' },
    { code: 'el', name: 'Ελληνικά', flag: '🇬🇷' },
    { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
    { code: 'ar', name: 'العربية', flag: '🇸🇦' },
    { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
    { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
    { code: 'th', name: 'ไทย', flag: '🇹🇭' },
    { code: 'pl', name: 'Polski', flag: '🇵🇱' },
    { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
    { code: 'no', name: 'Norsk', flag: '🇳🇴' },
    { code: 'da', name: 'Dansk', flag: '🇩🇰' },
    { code: 'fi', name: 'Suomi', flag: '🇫🇮' },
  
];

export function t(key) {
    const lang = translations[state.language] || translations['en'];
    return lang[key] || translations['en'][key] || key;
}

const listeners = new Set();

export function subscribe(listener) {
    listeners.add(listener);
    return () => listeners.delete(listener);
}

function notify() {
    listeners.forEach(listener => listener(state));
}

// Load data from API
export async function loadData() {
    try {
        const [categories, products] = await Promise.all([
            fetchCategories(),
            fetchProducts(),
        ]);
        state.categories = categories;
        state.products = products;
        // Set default category to the first one
        if (categories.length > 0 && !state.category) {
            state.category = categories[0].category_id;
        }
        state.loading = false;
        notify();
    } catch (err) {
        console.error('Failed to load data:', err);
        state.loading = false;
        notify();
    }
}

// Actions
export function setView(view) {
    state.view = view;
    notify();
}

export function setCategory(id) {
    state.category = id;
    notify();
}

export function addToCart(product, quantity = 1) {
    const existing = state.cart.find(item => item.product.product_id === product.product_id);

    if (existing) {
        existing.quantity += quantity;
    } else {
        state.cart.push({
            product,
            quantity,
            id: Date.now()
        });
    }
    notify();
}

export function updateQuantity(cartItemId, delta) {
    const item = state.cart.find(i => i.id === cartItemId);
    if (item) {
        item.quantity += delta;
        if (item.quantity <= 0) {
            removeFromCart(cartItemId);
            return;
        }
    }
    notify();
}

export function removeFromCart(cartItemId) {
    state.cart = state.cart.filter(item => item.id !== cartItemId);
    notify();
}

export function clearCart() {
    state.cart = [];
    state.tip = 0;
    notify();
}

export function processTip(amount) {
    state.tip = amount;
    notify();
}

export function startOrdering(type) {
    state.orderType = type;
    state.view = 'menu';
    notify();
}

export function completePayment(method, targetView = 'payment') {
    state.paymentMethod = method;
    state.view = targetView;
    notify();
}

export function setLanguage(lang) {
    state.language = lang;
    notify();
}

export function setPaymentMethod(method) {
    state.paymentMethod = method;
    notify();
}

export function resetSession() {
    state.cart = [];
    state.tip = 0;
    state.orderNumber = null;
    state.orderType = 'eat-in';
    state.paymentMethod = 'card';
    state.view = 'attract';
    state.language = 'en';
    notify();
}

export function setOrderNumber(num) {
    state.orderNumber = num;
    notify();
}

// Getters
export function getCartTotal() {
    const itemsTotal = state.cart.reduce((total, item) => {
        return total + (parseFloat(item.product.price) * item.quantity);
    }, 0);
    return itemsTotal + state.tip;
}

export function getCartCount() {
    return state.cart.reduce((count, item) => count + item.quantity, 0);
}
